#!/usr/bin/env python3
"""Stage Team Nexus Hermes profile files from canonical repo profile dirs.

The profile spec is a roster and invariant source, not a replacement schema for
Hermes config.yaml. Each profile owns native, hand-maintainable files under
profiles/<profile>/:

- SOUL.md
- AGENTS.md
- config.yaml

Rendering/staging copies SOUL.md and config.yaml unchanged, and composes AGENTS.md
from shared/profile/AGENTS.base.md plus the profile-specific AGENTS.md fragment.
Default mode is dry-run. Use --write with --output-dir to materialize staged
files. The renderer refuses to write directly into runtime-owned Hermes homes.
"""
from __future__ import annotations

import argparse
import hashlib
import importlib.util
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SPEC = ROOT / "profiles" / "team-nexus.profiles.yaml"
SHARED_AGENTS_BASE = ROOT / "shared" / "profile" / "AGENTS.base.md"
MANAGED_FILES = ("SOUL.md", "AGENTS.md", "config.yaml")


def load_validator_module():
    path = ROOT / "scripts" / "validate-profile-spec.py"
    spec = importlib.util.spec_from_file_location("team_nexus_profile_validator", path)
    if spec is None or spec.loader is None:
        raise SystemExit(f"cannot load validator module from {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def read_text(path: Path) -> str:
    return path.read_text().rstrip() + "\n"


def source_dir_for(profile_name: str, profile: dict[str, Any]) -> Path:
    source_dir = profile.get("source_dir") or f"profiles/{profile_name}"
    path = ROOT / source_dir
    if not path.exists():
        raise FileNotFoundError(f"profile source_dir does not exist for {profile_name}: {source_dir}")
    return path


def compose_agents(profile_name: str, profile: dict[str, Any], profile_agents: str) -> str:
    base = read_text(SHARED_AGENTS_BASE) if SHARED_AGENTS_BASE.exists() else ""
    role_manifest = profile.get("skills", {}).get("role_manifest", "none")
    header = (
        f"<!-- Generated by scripts/render-profile-spec.py from shared/profile/AGENTS.base.md "
        f"and {profile.get('source_dir', f'profiles/{profile_name}')}/AGENTS.md. -->\n\n"
        f"# {profile.get('display_name', profile_name.title())} generated operating context\n\n"
        f"Profile: `{profile_name}`\n"
        f"One job: {profile.get('one_job', 'Team Nexus profile')}\n"
        f"Role manifest: `{role_manifest}`\n\n"
    )
    parts = [header]
    if base:
        parts.append(base)
        parts.append("\n---\n\n")
    parts.append(profile_agents)
    return "".join(parts).rstrip() + "\n"


def rendered_files(data: dict[str, Any], args: argparse.Namespace) -> dict[Path, str]:
    profiles = data["profiles"]
    rendered: dict[Path, str] = {}
    for name, profile in profiles.items():
        if args.active_only and profile.get("status") != "active_v1":
            continue
        source_dir = source_dir_for(name, profile)
        profile_root = Path(name)
        rendered[profile_root / "SOUL.md"] = read_text(source_dir / "SOUL.md")
        rendered[profile_root / "config.yaml"] = read_text(source_dir / "config.yaml")
        rendered[profile_root / "AGENTS.md"] = compose_agents(name, profile, read_text(source_dir / "AGENTS.md"))
    return rendered


def digest(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()[:12]


def assert_safe_output_dir(output_dir: Path) -> None:
    resolved = output_dir.resolve()
    agents_dir = (ROOT / "agents").resolve()
    if resolved == agents_dir or agents_dir in resolved.parents:
        raise SystemExit(f"refusing to write rendered profiles into disposable ./agents directory: {resolved}")


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--spec", default=str(DEFAULT_SPEC), help="profile spec path")
    parser.add_argument("--mode", choices=("host", "docker"), default="host", help="staging label only; native config is copied unchanged")
    parser.add_argument("--active-only", action="store_true", default=True, help="render only active_v1 profiles")
    parser.add_argument("--include-planned", action="store_false", dest="active_only", help="also render planned inactive profiles")
    parser.add_argument("--write", action="store_true", help="write rendered files to --output-dir")
    parser.add_argument("--output-dir", default="", help="staging directory for --write")
    args = parser.parse_args(argv[1:])

    validator = load_validator_module()
    spec_path = Path(args.spec)
    if not spec_path.is_absolute():
        spec_path = Path.cwd() / spec_path
    validator.validate_spec(spec_path)
    data = validator.load_yaml(spec_path)

    files = rendered_files(data, args)
    if args.write:
        if not args.output_dir:
            print("--write requires --output-dir", file=sys.stderr)
            return 2
        output_dir = Path(args.output_dir)
        if not output_dir.is_absolute():
            output_dir = Path.cwd() / output_dir
        assert_safe_output_dir(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        for rel, content in files.items():
            target = output_dir / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content)
        print(f"staged {len(files)} files to {output_dir}")
    else:
        print(f"dry-run: would stage {len(files)} files for mode={args.mode}")
        for rel, content in sorted(files.items()):
            print(f"{rel} sha256:{digest(content)} bytes:{len(content.encode())}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
